creando estructura html
ErnestoLeon87/angular-study pull request #21
Opened 2022-05-04 00:07 UTC by lesaygit

2022-05-04 00:09 UTC, lesaygit commented on src/app/tareas/tareas.component.html
> +-->
podriamos usar una tabla?

2022-05-04 00:10 UTC, lesaygit commented on src/app/tareas/tareas.component.ts
> +}
es mas conveniente un conponente tareas.

2022-05-04 02:37 UTC, ErnestoLeon87 requested changes

2022-05-04 02:37 UTC, ErnestoLeon87 commented on src/app/tareas/tareas.component.html
> +-->
con una tabla se puede hacer, pero eso nos complicaria mucho, ademas las tablas estan concebidas para listar datos, que nuestro caso lo que estamos buscando es una estructura en el html. Entonces lo que vamos a hacer trabajar con los divs que ya pusite ahi.

2022-05-04 02:37 UTC, ErnestoLeon87 commented on src/app/tareas/tareas.component.scss
> +    background-color: rgb(245, 228, 186);
- usa una variable de scss para almacenar el color y guardala en un archivo variables.scss dentro de una carpeta share en la raiz del projecto.
- haz lo mismo para el color de en proceso y terminadas.
- utiliza el sistem exadecimal para los colores en vez de la funcion rgb.

2022-05-04 02:37 UTC, ErnestoLeon87 commented on src/app/tareas/tareas.component.scss
> +.tarea {
En el caso de que vayamos a darle mas estilos a las tareas individuales, esta clase iria dentro de container.

2022-05-04 02:37 UTC, ErnestoLeon87 commented on src/app/tareas/tareas.component.scss
> +    width: 30%;
cada tarea debe ocupar el 100% de la seccion en la que se encuentre,

2022-05-04 02:37 UTC, ErnestoLeon87 commented on src/app/tareas/tareas.component.ts
> +export class TareasComponent  {
es un poco confuso que este componente se llame Tareas, aunque lo que estamos listando son tareas, no es lo unico que este componente eta haciendo, porque tambien las esta organizando, entoces este nombre no cubre todo el sentido de este componente. 
- Renombra este componente eg.: (Pizarra) en vez de Tareas.

2022-05-05 12:39 UTC, ErnestoLeon87 requested changes

2022-05-05 12:39 UTC, ErnestoLeon87 commented on src/app/app.module.ts
> +
falta la declaracion del component Pizarra

2022-05-05 12:39 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.html
> +    <div class="tarea nuevas"></div>
Te falto el titulo de cada seccion como lo muestra el diseno

2022-05-05 12:39 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.scss
> +        width: 100%;
no creo que necesites darle un width de 100% a cada columna, prueba quitandole ese width a ver como se comporta

2022-05-05 12:39 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.scss
> +    .tarea {
este nombre que le pusiste a esta clase es confuso. creo que "tarea-container" tendria mas sentido

2022-05-05 14:22 UTC, ErnestoLeon87 requested changes

2022-05-05 14:22 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.scss
> +    .tarea_container{
Creo que puedes estructurar esta clase mejor
algo como esto 

`.tarea_container {
...
&.nueva{}
&.proceso{}
&.ternimada{}
}`

en vez de dejarlas fuera de la clase tarea_container, estas clases quien unico las va a user es tarea_container.

2022-05-12 01:56 UTC, ErnestoLeon87 approved these changes

2022-05-12 01:57 UTC, merged