listando las tareas del svc.
ErnestoLeon87/angular-study pull request #25
Opened 2022-05-15 02:46 UTC by lesaygit

2022-05-16 20:43 UTC, ErnestoLeon87 requested changes

2022-05-16 20:43 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.ts
> +  tareasPendientes!: Tarea[];
estos arrays no los necesitamos

2022-05-16 20:43 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.ts
> +  constructor(private tareasSvc: TareaService) { }
renombra tareasSvc a tareasService

2022-05-16 20:43 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.ts
> +    this.tareasPendientes$.pipe(
estas subscriptiones se pueden reemplazar por async pipe, asi dejamos a async pipe que se des-subscriba de cada observable 
Elimina estas subscripciones, y usa async pipe.

2022-05-16 20:43 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.ts
> +    this.tareasPendientes$ = this.tareas$
extrae estos tres filters para un metodo privado que se llame filtrarTareas()

y luego lo llamas en ngOnInit

2022-05-16 20:43 UTC, ErnestoLeon87 commented on src/app/tarea/tarea.component.ts
> +  tarea!:Tarea;
no creo que sea necesario el non-null assertion operator (!), prueba borrarlo a ver que te dice

2022-05-16 20:43 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.ts
> +  tareas$!: Observable<Tarea[]>;
no creo que sea necesario el non-null assertion operator (!), prueba borrarlo a ver que te dice

2022-05-16 20:43 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.ts
> +      .pipe(map(val => val.filter(dat => dat.status === 'PENDIENTE')));
en vez de user un string usa el enum de TareaStatus que creaste

2022-05-17 02:06 UTC, lesaygit commented on src/app/pizarra/pizarra.component.ts
> -import { filter, Observable, map, tap } from 'rxjs';
retire el operador filter ya que el usado es el de  la funcion filter sobre arrays.

2022-05-18 21:17 UTC, merged