creando tarea dialog
ErnestoLeon87/angular-study pull request #29
Opened 2022-05-22 08:01 UTC by lesaygit

2022-05-22 08:04 UTC, lesaygit commented on src/app/pizarra/pizarra.component.scss
> +        max-width: 420px;
fijando el tamaño del container tarea.

2022-05-23 16:12 UTC, ErnestoLeon87 requested changes

2022-05-23 16:12 UTC, ErnestoLeon87 commented on src/app/app-routing.module.ts
> +  {path:'tareadialog',component:TareaDialogComponent},
este dialog no va a ser parte de la navegacion.
Elimina tarea-dialog component del route array

2022-05-23 16:12 UTC, ErnestoLeon87 commented on src/app/tarea-dialog/tarea-dialog.component.html
> +    <input matInput>
Yo no recuerdo haberlo especificado en el issue.
1. Adiciona validaciones al formulario. para el titulo que no sea mas que 30 caracteres y no puede contener nungun html o javascrit. y para la description que no sea mas de 250 caracteres.
Para hacer esto debes estudiarte FormBuilder de angular.

2022-06-10 00:53 UTC, ErnestoLeon87 commented on src/app/material.module.ts
> +    exports:[MatToolbarModule,MatButtonModule,MatCardModule,MatDialogModule,
podrias formatear este codigo?
eg. 
[
   MatToolbar,
   MatButton,
   ...
]

2022-06-10 00:53 UTC, ErnestoLeon87 commented on src/app/pizarra/pizarra.component.scss
> +        max-width: 420px;
por que tuviste que fija el tamano del container?

2022-06-10 20:56 UTC, ErnestoLeon87 approved these changes

2022-06-10 20:57 UTC, merged