agregando tareas
ErnestoLeon87/angular-study pull request #33
Opened 2022-06-25 04:30 UTC by lesaygit

2022-07-03 04:04 UTC, lesaygit commented on src/app/core/tareas.service.ts
> -      catchError(err => throwError(() => new Error('Problemas de conectividad...')
en ves de usar unobserv de creacion como throwError, simplemente levante una exeption...

2022-07-06 15:07 UTC, ErnestoLeon87 requested changes

2022-07-06 15:07 UTC, ErnestoLeon87 commented on src/app/core/tarea.interface.ts
> +    id?: number;
Por que tuviste que marcar id como posible undefined?

2022-07-06 15:07 UTC, ErnestoLeon87 commented on src/app/core/tareas.service.ts
> +      catchError(err =>{throw new Error("Proceso invalido, problemas con la API-Tareas.");
1. Elimina las llaves para que todo este inline.
2. Estudiate esto para que veas como se manejan los errores: https://rxjs.dev/api/operators/catchError.
3. Simula un error a ver como se comporta la app.

2022-07-08 01:33 UTC, ErnestoLeon87 requested changes

2022-07-08 01:33 UTC, ErnestoLeon87 commented on src/app/core/tarea.interface.ts
> +    id?: number;
no creo que el id sea undefined, pero bueno lo puedes dejar asi

2022-07-08 01:33 UTC, ErnestoLeon87 commented on src/app/core/tareas.service.ts
> +  private postUrl = 'http://localhost:9000/api/tarea';//porque no poner la url completa asi? y nos ahorramos la variable del metodo.?
porque son diferentes urls en cada methodo.
revertir este cambio

2022-07-08 01:33 UTC, ErnestoLeon87 commented on src/app/core/tareas.service.ts
> +      .pipe(tap((tareas: Tarea[]) => {
revertir este cambio, elimina estas llaves

2022-07-08 01:33 UTC, ErnestoLeon87 commented on src/app/core/tareas.service.ts
> +  tareasArrary: Tarea[] = [];
esta variable puede ser eliminada

2022-07-08 22:14 UTC, merged